
package Front;

import java.util.ArrayList;
import javax.swing.JLabel;
import practica2vaqueras.Moto;
import practica2vaqueras.Productos;
import practica2vaqueras.Recorrido;


public class Entregas extends javax.swing.JFrame {
 private ArrayList<Productos> productos = new ArrayList<>();
 private ArrayList<Moto> vehiculos = new ArrayList<>(); 
 public static int Distancia1=0;
 public static int Distancia2=0;
 public static int Distancia3=0;
 
    public Entregas(ArrayList<Productos> productos, ArrayList<Moto> vehiculos) {
        initComponents();
        this.productos=productos;
        this.vehiculos= vehiculos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moto2 = new javax.swing.JLabel();
        moto3 = new javax.swing.JLabel();
        moto1 = new javax.swing.JLabel();
        bmoto1 = new javax.swing.JButton();
        bmoto2 = new javax.swing.JButton();
        bmoto3 = new javax.swing.JButton();
        EnviarTodos = new javax.swing.JButton();
        Meta = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moto.png"))); // NOI18N
        moto2.setText("jLabel1");

        moto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moto.png"))); // NOI18N
        moto3.setText("jLabel1");

        moto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moto.png"))); // NOI18N
        moto1.setText("jLabel1");

        bmoto1.setText("Enviar");
        bmoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmoto1ActionPerformed(evt);
            }
        });

        bmoto2.setText("Enviar");
        bmoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmoto2ActionPerformed(evt);
            }
        });

        bmoto3.setText("Enviar");
        bmoto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmoto3ActionPerformed(evt);
            }
        });

        EnviarTodos.setText("Enviar Todos");
        EnviarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarTodosActionPerformed(evt);
            }
        });

        Meta.setBackground(new java.awt.Color(204, 0, 0));
        Meta.setOpaque(true);

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bmoto2)
                            .addComponent(bmoto3)
                            .addComponent(bmoto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moto3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Menu)
                        .addGap(217, 217, 217)
                        .addComponent(EnviarTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(moto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(bmoto1)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bmoto2)
                        .addGap(18, 18, 18)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moto3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bmoto3)
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarTodos)
                    .addComponent(Menu))
                .addContainerGap())
            .addComponent(Meta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        MenuPrinicipal menu = new MenuPrinicipal(productos, vehiculos);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void EnviarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarTodosActionPerformed
        // TODO add your handling code here:
        Recorrido recorrido = new Recorrido(moto1, Distancia1);
        Recorrido recorrido2 = new Recorrido(moto2, Distancia2);
        Recorrido recorrido3 = new Recorrido(moto3 , Distancia3);        
        recorrido.start();
        recorrido2.start();
        recorrido3.start();
    }//GEN-LAST:event_EnviarTodosActionPerformed

    private void bmoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmoto1ActionPerformed
        // TODO add your handling code here:
        Recorrido recorrido = new Recorrido(moto1,Distancia1);
        recorrido.start();
        
    }//GEN-LAST:event_bmoto1ActionPerformed

    private void bmoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmoto2ActionPerformed
        // TODO add your handling code here:
        Recorrido recorrido2 = new Recorrido(moto2, Distancia2);
        recorrido2.start();
    }//GEN-LAST:event_bmoto2ActionPerformed

    private void bmoto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmoto3ActionPerformed
        // TODO add your handling code here:
         Recorrido recorrido3 = new Recorrido(moto3 , Distancia3);
         recorrido3.start();
    }//GEN-LAST:event_bmoto3ActionPerformed

  public JLabel getMeta(){
  return Meta;
  }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarTodos;
    private javax.swing.JButton Menu;
    public static javax.swing.JLabel Meta;
    private javax.swing.JButton bmoto1;
    private javax.swing.JButton bmoto2;
    private javax.swing.JButton bmoto3;
    private javax.swing.JLabel moto1;
    private javax.swing.JLabel moto2;
    private javax.swing.JLabel moto3;
    // End of variables declaration//GEN-END:variables
}
