
package Front;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import practica2vaqueras.Moto;
import practica2vaqueras.Productos;

public class MenuPrinicipal extends javax.swing.JFrame {

  Fondo fondo = new Fondo();
  ArrayList<Productos> productos = new ArrayList<>();
        ArrayList<Moto> vehiculos = new ArrayList<>();
  
    public MenuPrinicipal(ArrayList<Productos> productos, ArrayList<Moto> vehiculos) {
       
 this.setContentPane(fondo);
        initComponents();
        this.productos = productos;
        this.vehiculos= vehiculos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new Fondo();
        Pedidos = new javax.swing.JButton();
        Entregas = new javax.swing.JButton();
        Historial = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setPreferredSize(new java.awt.Dimension(680, 424));

        Pedidos.setText("Pedidos");
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });

        Entregas.setText("Entregas");
        Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregasActionPerformed(evt);
            }
        });

        Historial.setText("Historial de entregas");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Entregas)
                            .addComponent(Pedidos)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(Historial)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Pedidos)
                .addGap(55, 55, 55)
                .addComponent(Entregas)
                .addGap(42, 42, 42)
                .addComponent(Historial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(Salir))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
        // TODO add your handling code here:
        Pedidos pedidos = new Pedidos(productos, vehiculos);
        
        pedidos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_PedidosActionPerformed

    private void EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregasActionPerformed
        // TODO add your handling code here:
        Entregas entregas = new Entregas(productos, vehiculos);
        entregas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntregasActionPerformed

    /**
     * @param args the command line arguments
     */
  /**  public class Imagen extends javax.swing.JPanel{
        
    public Imagen(){
    this.setSize(405,405);
    }
    
    public void paint(Graphics grafico){
        Dimension height = getSize();
        ImageIcon img = new ImageIcon(getClass().getResource("NetBeansProjects\\Practica2Vaqueras\\src\\pngwing.com.png"));
        grafico.drawImage(img.getImage(), 0, 0, height.width, height.height, null);
        setOpaque(false);
        super.paintComponent(grafico);
    }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entregas;
    private javax.swing.JButton Historial;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Pedidos;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables

    class Fondo extends JPanel{
    private Image imagen;
    
        public void paint(Graphics g){
        imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo.png")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
}
